# Generated by Django 5.0 on 2024-01-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0007_rename_ususario_fotografia_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="publicada",
            field=models.BooleanField(default=True),
        ),
    ]
