# Generated by Django 5.0 on 2024-01-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0006_fotografia_ususario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fotografia", old_name="ususario", new_name="usuario",
        ),
    ]
